package com.dkd.emms.systemManage.bo;

/**
 * 仓库--组织机构关联实体
 * @author wangqian
 *
 */
public class WareHouseOrg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZSH.B_WAREHOUSE_ORG.WAREHOUSE_ID
     *
     * @mbggenerated Sat Feb 18 14:37:08 CST 2017
     */
    private WareHouse  wareHouse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZSH.B_WAREHOUSE_ORG.ORG_ID
     *
     * @mbggenerated Sat Feb 18 14:37:08 CST 2017
     */
    private Organization organization;

	public WareHouse getWareHouse() {
		return wareHouse;
	}

	public void setWareHouse(WareHouse wareHouse) {
		this.wareHouse = wareHouse;
	}

	public Organization getOrganization() {
		return organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}
}